// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk8yiNciUpr5Vjjd5dsRFcXwqOdwo67xM',
    appId: '1:445026731312:web:bb2441790dafe37b9934f5',
    messagingSenderId: '445026731312',
    projectId: 'petpal-app-ec0a8',
    authDomain: 'petpal-app-ec0a8.firebaseapp.com',
    storageBucket: 'petpal-app-ec0a8.appspot.com',
    measurementId: 'G-S6M6LMP4BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnt5iv0fz0nYALRls9hFAl5Iu8MTtVL0',
    appId: '1:445026731312:android:21341900836015ef9934f5',
    messagingSenderId: '445026731312',
    projectId: 'petpal-app-ec0a8',
    storageBucket: 'petpal-app-ec0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HhpVJ9OVkfOMsSZ-NBvy_Eqrz5sWTKM',
    appId: '1:445026731312:ios:0f3196beb096a7509934f5',
    messagingSenderId: '445026731312',
    projectId: 'petpal-app-ec0a8',
    storageBucket: 'petpal-app-ec0a8.appspot.com',
    iosClientId: '445026731312-tjuvrpsurjqrkpql8sboe5g87i275047.apps.googleusercontent.com',
    iosBundleId: 'com.example.petpalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HhpVJ9OVkfOMsSZ-NBvy_Eqrz5sWTKM',
    appId: '1:445026731312:ios:0f3196beb096a7509934f5',
    messagingSenderId: '445026731312',
    projectId: 'petpal-app-ec0a8',
    storageBucket: 'petpal-app-ec0a8.appspot.com',
    iosClientId: '445026731312-tjuvrpsurjqrkpql8sboe5g87i275047.apps.googleusercontent.com',
    iosBundleId: 'com.example.petpalApp',
  );
}
